  0%|          | 0/10 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/tefan/projects/BachModels/src/train.py", line 123, in <module>
    trainer.train()
  File "/home/tefan/projects/BachModels/src/train.py", line 74, in train
    train_loss, train_cer, train_wer = self.train_epoch()
                                       ^^^^^^^^^^^^^^^^^^
  File "/home/tefan/projects/BachModels/src/train.py", line 50, in train_epoch
    output_logits, sampled_ids, loss = self.model.forward_teacher_forcing(inputs, labels)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tefan/projects/BachModels/src/model.py", line 257, in forward_teacher_forcing
    logits = self.decoder.forward_teacher_forcing(memory, targets)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tefan/projects/BachModels/src/model.py", line 188, in forward_teacher_forcing
    out = self.decoder(
          ^^^^^^^^^^^^^
  File "/home/tefan/projects/BachModels/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tefan/projects/BachModels/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TransformerDecoder.forward() got an unexpected keyword argument 'tgt_key_masking'